name: generate animation

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 * * * *"

  # allows to manually run the job at any time
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/green.svg?color_snake=#00e6de&color_dots=#787c81,#4c9668,#46aa65,#23a348,#259946
            dist/transparent.svg?color_snake=#f7860f&color_dots=transparent,#A188F2,#683EF0,#603AE1,#5231BD
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
